namespace TimeMemoria.Windows.Native;

/// <summary>
/// The same answers the ImGui Help tab gives — behaviour that looks like a bug
/// and is not, plus what the plugin will never do.
/// </summary>
public class HelpPanelNode : TextLinesPanelNode
{
  protected override List<string> BuildLines() =>
  [
    "Why is a whole expansion greyed out?",
    "   You have not reached it yet, so its name and counts are hidden.",
    "   Settings > Spoiler Mode shows them anyway. Free Trial Mode is",
    "   separate and cannot be overridden — there is nothing there to reveal.",
    "Why does a quest say \"Pre-Plugin\" instead of a date?",
    "   It was already complete when the plugin was first installed, so there",
    "   is no record of when you did it. Anything since is dated properly.",
    "Why is my playtime blank or out of date?",
    "   The game only reveals total playtime in the reply to /playtime, and",
    "   this plugin will not run commands for you. Type it yourself and the",
    "   figure is captured. The age beside it is when that happened.",
    "Why is session pacing empty?",
    "   It measures quests completed since you logged in. Until you finish",
    "   one this session there is nothing to average.",
    "Where do the percentages come from?",
    "   Quests your character can never take — the starting city and class",
    "   routes you did not pick, the Grand Company you did not join — are left",
    "   out. Two characters can legitimately show different totals.",
    "Why do collectables say \"open Achievements once\"?",
    "   The game keeps no running count. The number lives in an achievement and",
    "   the client only fetches it for whichever one you are looking at, so the",
    "   plugin waits until you open the Achievements window rather than asking",
    "   the server itself.",
    "   A figure with a + is a floor, not a count: a tier you have already",
    "   finished reports its own requirement instead of your total. Look at a",
    "   later tier for the exact number.",
    "The Wiki button beside the quest search",
    "   Sends whatever you have typed to the FFXIV wiki's own search, which",
    "   jumps straight to a page when the text matches one exactly. That makes",
    "   community shorthand work — A8S, TEA, DRS and the like are wiki",
    "   redirects, so they land on the right page even though none of them is a",
    "   quest name and searching quests for them finds nothing.",
    "   With the box empty it opens the wiki's Main Scenario index instead —",
    "   the story in order, which is the page most often wanted anyway.",
    "Why does Overview show a smaller total than the Quests tree?",
    "   Overview honours the exclusion settings — an excluded category is shown",
    "   greyed and left out of the totals. The tree never excludes anything,",
    "   because it is how you reach a quest, and dropping a category from a",
    "   total should not put its quests out of reach.",
    "An event is running in game but not listed. Or the reverse.",
    "   Active Events reads the client, so anything switched on shows up even",
    "   if no article announced it. End dates come from the Lodestone feed,",
    "   so an event the feed missed appears without one.",
    "Where does my exported data go?",
    "   Onto your clipboard, and nowhere else. The only network request this",
    "   plugin makes is fetching the public Lodestone news feed.",
    "Commands",
    "   /timememoria    the window chosen in Settings  (/tm for short)",
    "   /tm classic     the classic window, whichever is chosen",
    "   /tm native      this window, whichever is chosen",
    "   /tmmini         playtime, pacing and jobs, in a small window",
    "   /tm reset       rebuild the quest tree",
    "   The plugin registers these; it never sends commands itself.",
    "What this plugin will never do",
    "   No damage meters, combat logs or duty results.",
    "   No automation, and no commands issued on your behalf.",
    "   No toasts or overlays interrupting your play.",
    "   No reading of other characters' data.",
    "   It is a notebook, not a scoreboard. If a feature request needs any of",
    "   the above, it will be declined.",
    "Something wrong, or missing?",
    "   Miscounts and missing quests are worth reporting — quest data changes",
    "   with every patch and this cannot all be tested by hand.",
    "   github.com/LegendsOfTheGame/TimeMemoriaV3/issues",
    "   For clickable links, open the classic window: /tm classic"
  ];

}
